Krylov schur
msmdev/msmtools pull request #2
Opened 2020-04-28 16:40 UTC by Marius1311

Hi all, I thought I would open this PR to start the discussion. The changes introduced so far come from @michalk8, I think they regard mostly sparsification and some minor changes. We can use this as a basis for our skype call tomorrow in case @msmdev you decide to join.

2020-04-28 16:56 UTC, Marius1311 commented
@michalk8, I'm writing down comments as I'm checking out your code:
- initialising with a sparse transition matrix and not using krylov currently raises an error, I would opt for a warning and densifying
- even though I have `self.method = 'brandts`,  I still get `ModuleNotFoundError: No module named 'slepc4py'` from `sorted_schur.py`. In `top_eigenvalues`, we *always* use PETSc and SLEPSc to compute the top eigenvalues, irrespective of the `method`. I wouldn't do this, otherwise the user will always need to have these packages installed. Also, the speedup will be minimal for the top eigenvalues of a sparse matrix - I would strongly recommend to use `scipy.sparse.linalg.eigs` here.

2020-04-28 16:58 UTC, Marius1311 commented
In fact, I couldn't get SLEPSc installed on my mac, so I can't easily move on.

2020-04-28 17:01 UTC, michalk8 commented
Regarding the method, I think it's because of the eigendecomposition which is also being calculated by SLEPc.
I'm trying to setup everything on the server so that you can continue, but there are some issues as well. Will let you know.

2020-04-28 17:16 UTC, msmdev commented
Hi, 
sorry, I don't remember that we have a Skype appointment tomorrow. Could you update me on this, please?
Some warnings: There are some things in setup.py that I just changed for myself and for convenience reasons - we mb. should use the version from the devel branch there...
Also, I commented the import of some modules out, since I had problems with this...
I didn't look into using sparse matrices so far - there are related issues.
Regarding the top eigenvalues: I have to rethink this - in the sense that brandts should work without slepc - but we can't use `scipy.sparse.linalg.eigs` here, since it produces awfully bad eigenvalues (they are very often wrong!). We can't work with this.
Generally, the topic of eigenvalues and raises and/or warnings is difficult - we should discuss this before changing stuff there. It's intricate and performance shouldn't overrule sanity here...

2020-04-28 17:30 UTC, msmdev commented
@michalk8 Please don't raise a `RuntimeError`, if the stationary distribution in `GPCCA.optimize` can't be calculated, since not everyone wants/needs this... It will reduce usability.

2020-04-28 17:37 UTC, msmdev commented
@michalk8 The default method in `sorted_schur` shouldn't be `scipy` but `brandts`, since this often sorts to few eigenvalues (less than requested) without a reason (just by chance? at least I don't see a reason for this behavior.).

2020-04-28 17:39 UTC, msmdev commented
@Marius1311 I found the email regarding Skype tomorrow at 18:00  and will try to join :)

2020-05-01 18:07 UTC, Marius1311 commented
Hi all! Finally being able to use SLEPSc thanks to @michalk8 , here is a list of comments:
- as discussed, if `method != 'krylov'`, I wouldn't use SLEPSc to compute the eigenvalues prior to computing the Schur form. If we want to avoid `scipy.sparse.linalg.eigs`, we can use `scipy.linalg.rsf2csf` to get the complex schur form from the real as @msmdev suggested, which will give us the eigenvalues. These can then be used to warn the user in case we split a block of complex conjugates
- `method = 'scipy'` always gives me E1 below, which seems to be caused by `slepc4py`
- In the example I'm looking at, `m = 6` would split a block of complex conjugates. With `method = 'krylov'`, this is correctly identified: `Clustering P into `6` clusters will split a pair of conjugate eigenvalues. Choose one cluster more or less.`. However, when I use `method = 'brandts'`, I get E2 instead. Did I somehow miss the warning message here? Why does the behaviour differ?
- if `method='krylov'` but a dense matrix is passed, a warning may be nice to tell the user how to take advantage of SLEPSc
- I noticed fine differences between `method='brandts'` and `method='krylov'` for `m=2` in the memberships, but so small that `np.allclose` with default parameters still returns `True`. I only noticed this because when I plotted the memberships in the embedding, scvelo by default used a different colormap for one of the memberships that brandts gave. I don't know whether this means anything. 


## E1
```python
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-26-5e22fe6c99aa> in <module>
      1 # method = 'scipy'
      2 gpcca = GPCCA(kernel_fwd.transition_matrix.A, method='scipy')
----> 3 gpcca.optimize(3)

~/Projects/msmtools/msmtools/analysis/dense/gpcca.py in optimize(self, m, return_extra)
   1324         # Calculate Schur matrix R and Schur vector matrix X, if not adequately given.
   1325 
-> 1326         self._do_schur_helper(max(m_list))
   1327 
   1328         # Initialize lists to collect results.

~/Projects/msmtools/msmtools/analysis/dense/gpcca.py in _do_schur_helper(self, m)
   1127                     self.X, self.R = _do_schur(self.P, self.eta, m, self.z, self.method)
   1128             else:
-> 1129                 self.X, self.R = _do_schur(self.P, self.eta, m, self.z, self.method)
   1130 
   1131     def minChi(self, m_min, m_max):

~/Projects/msmtools/msmtools/analysis/dense/gpcca.py in _do_schur(P, eta, m, z, method)
    250         Q = sorted_schur(P_bar, m, z, method) #Pbar!!!
    251     else:
--> 252         R, Q = sorted_schur(P_bar, m, z, method) #Pbar!!!
    253         if m - 1 not in _find_twoblocks(R):
    254             warnings.warn("Coarse-graining with " + str(m) + " states cuts through "

~/Projects/msmtools/msmtools/util/sorted_schur.py in sorted_schur(P, m, z, method)
    491             warnings.warn("Reordering of Schur matrix was inaccurate.")
    492     elif method == 'scipy':
--> 493         R, Q = sorted_scipy_schur(P, m, z=z)
    494     elif method == 'krylov':
    495         Q, _, _ = sorted_krylov_schur(P, m, z=z)

~/Projects/msmtools/msmtools/util/sorted_schur.py in sorted_scipy_schur(P, m, z)
    213         #cutoff = (np.abs(eigenval_in) + np.abs(eigenval_out)) / 2.0
    214         cutoff = np.abs(top_eigenvals[m-1]) - 0.2
--> 215         smallest_eigenval = np.abs(smallest_eigenvalue(P, z='SM'))
    216         if cutoff < smallest_eigenval:
    217             cutoff = smallest_eigenval

~/Projects/msmtools/msmtools/util/sorted_schur.py in smallest_eigenvalue(P, z)
    163         warnings.warn("The number of converged eigenpairs is too small.")
    164     # Get the smallest eigenvalue.
--> 165     smallest_eigenval = E.getEigenvalue(0)
    166 
    167     return smallest_eigenval

SLEPc/EPS.pyx in slepc4py.SLEPc.EPS.getEigenvalue()

Error: error code 63
[0] EPSGetEigenvalue() line 450 in /Users/marius/slepc-3.13.1/src/eps/interface/epssolve.c
[0] Argument out of range
[0] Argument 2 out of range
```

## E2
```python
According to scipy.linalg.subspace_angles() X isn't an invariant subspace of P, since the subspace angles between the column spaces of P*X and X*R (resp. X, if you chose the Krylov-Schur method)aren't near zero. The subspace angles are: `[6.78576644e-03 2.42416841e-15 2.17546739e-15 1.91024389e-15
 1.58665000e-15 7.86412512e-16]`
```

2020-05-03 12:08 UTC, msmdev requested changes
Please address the comments before I can merge - thx! :-)

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +_default_schur_method = 'scipy'
```suggestion
_default_schur_method = 'brandts'
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +def _initliaze_matrix(M, P):
```suggestion
def _initialize_matrix(M, P):
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +    _initliaze_matrix(M, P)
```suggestion
    _initialize_matrix(M, P)
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        raise ValueError(f"The number of rows `n={X.shape[0]}` of the Schur vector matrix X doesn't match "
Do we really want to use f string formating? This only works starting with python 3.6, which is a no-go in my opinion, since people are still using python 2. It can't be included by from __future__ import ... but mb. there is a package (I saw future_fstrings somewhere ... mb. this solves the problem?).

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Invalid spectrum sorting options `{z}`. Valid options are: `'LM'`, `'LR'`")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        warnings.warn(f"The number of converged eigenpairs `nconv={nconv}` is too small.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Invalid spectrum sorting options `{z}`. Valid options are: `'SM'`, `'SR'`")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Clustering P into `{m}` clusters will split "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Invalid spectrum sorting options `{z}`. Valid options are: `'LM'`, `'LR'`")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"`{m}` dominant eigenvalues (associated with the "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"According to scipy.linalg.subspace_angles() sorted Scipy-Schur didn't "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Clustering P into `{m}` clusters will split "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Invalid spectrum sorting options `{z}`. Valid options are: `'LM'`, `'LR'`")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        warnings.warn(f"The number of converged eigenpairs is `{nconv}`, but `{m}` clusters were requested.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"According to scipy.linalg.subspace_angles() Krylov-Schur didn't "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        warnings.warn(f"According to scipy.linalg.subspace_angles() Krylov-Schur didn't "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +                print(f"Unable to import PETSc or SLEPc.\n"
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        raise ValueError(f"Unknown method `{method!r}`.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        raise ValueError(f"According to scipy.linalg.subspace_angles() X isn't an invariant "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            raise ValueError(f"eta vector length ({len(eta)}) doesn't match with the shape of P {P.shape}.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                    raise ValueError(f"The first dimension of X is `{Xdim1}`. This doesn't match "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                    raise ValueError(f"The first dimension of X is `{Xdim1}`. This doesn't match "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                    raise ValueError(f"The first dimension of X is `{Xdim1}`. This doesn't match "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            raise ValueError(f"m_min ({m_min}) must be smaller than m_max ({m_max}).")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            raise ValueError(f"There is no point in clustering into `{m_min}` clusters.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                raise ValueError(f"m_min ({m[0]}) must be smaller than m_max ({m[1]}).")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                raise ValueError(f"m_min ({m_min}) must be smaller than m_max ({m_max}).")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            raise TypeError(f"Invalid type `{type(m).__name__}`.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            raise ValueError(f"Number of macrostates `m={max(m_list)}` exceeds number "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            raise ValueError(f"There is no point in clustering into `{m}` clusters.")
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                    warnings.warn(f"Coarse-graining with `{m}` states cuts through "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                warnings.warn(f"`{m}` macrostates requested, but transition matrix only has "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +                warnings.warn(f"Number of metastable states `m={m}` is too small. "
f string format issue

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +    _initliaze_matrix(M, P)
```suggestion
    _initialize_matrix(M, P)
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +    _initliaze_matrix(M, P)
```suggestion
    _initialize_matrix(M, P)
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +        dummy = dummy.A
```suggestion
        dummy = dummy.toarray()
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/util/sorted_schur.py
> +            if not _slepc_msg_show or True:
This if not construct is somehow diffuse to me - please reformulate more clearly... :)

2020-05-03 12:08 UTC, msmdev commented on setup.py
>      setup_requires=['numpy', 'cython'],
```suggestion
    setup_requires=['numpy', 'cython', 'setuptools_scm'],
```
I think you need to add this, if you want to use setuptools_scm. (but why are we using it?)

2020-05-03 12:08 UTC, msmdev commented on setup.py
> +    # cmdclass=get_cmdclass(),
I guess the issue with cmdclass stems from using setuptools instead of numpy.distutils...

2020-05-03 12:08 UTC, msmdev commented on setup.py
> +    # cmdclass=get_cmdclass(),
We shouldn't use setuptools at all, but numpy.distutils. 
The block

`if __name__ == '__main__':`
    `try:`
        `from setuptools import setup`
    `except ImportError:`
        `from distutils.core import setup`
    `setup(**metadata)`

 at the end should be replaced by

`if __name__ == '__main__':`
    `from numpy.distutils.core import setup`
    `setup(**metadata)`

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +    if not np.allclose(np.sum(P, 1), 1, rtol=1e-6, atol=1e-6):  # previously eps
```suggestion
    if not np.allclose(np.sum(P, 1), 1.0, rtol=1e-6, atol=1e-6):  # previously eps
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        # TODO @Marius: I'd decrease the tolerance, getting error here for 3+ MS states
1e-6 is already a pretty high tolerance... increasing this any higher appears risky to me. Before doing this, one should ask why there is such a high deviation from orthogonality here and check it carefully.

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        dummy = subspace_angles(dp.A if issparse(dp) else dp, X)
```suggestion
        dummy = subspace_angles(dp.toarray() if issparse(dp) else dp, X)
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        X = np.dot(sp.csr_matrix(chi.T), sp.dia_matrix(([eta], [0]), shape=(eta.shape[0], eta.shape[0])))
```suggestion
        V = np.dot(sp.csr_matrix(chi.T), sp.dia_matrix(([eta], [0]), shape=(eta.shape[0], eta.shape[0])))
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        X = np.dot(chi.T, np.diag(eta))
```suggestion
        V = np.dot(chi.T, np.diag(eta))
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +    A = X.dot(P).dot(chi)
```suggestion
    A = V.dot(P).dot(chi)
```

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +        self.eta = (np.ones(P.shape[0]) / P.shape[0]) if eta is None else eta
```suggestion
        if eta == None:
             self.eta = np.true_divide(np.ones(P.shape[0]), P.shape[0])
        else:
            self.eta = eta
```
I think this from adds some clarity. Also we need to keep in mind that / isn't doing true division in python 2.

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +    def optimize(self, m: Union[int, Tuple[int, int], List[int], Dict[str, int]],
Do we really need so much input type possibilities here? I think this creates unnecessary complexity and redundancy. int and dict are already enough. Mb one could add a tuple restricted to two items (Tuple[int, int] is exactly this, right?), but why would one need a list of possibly more than two elements?

2020-05-03 12:08 UTC, msmdev commented on msmtools/analysis/dense/gpcca.py
> +            return self, chi_list, rot_matrix_list, crispness_list
self.X and self.R are not accessible via properties (only the reduced forms self._X and self._R are). If one would like to access them one would need to look into the source code. Thus I gave them back, if full_output was requested.

2020-05-03 12:18 UTC, msmdev commented
> Hi all! Finally being able to use SLEPSc thanks to @michalk8 , here is a list of comments:
> 
> * as discussed, if `method != 'krylov'`, I wouldn't use SLEPSc to compute the eigenvalues prior to computing the Schur form. If we want to avoid `scipy.sparse.linalg.eigs`, we can use `scipy.linalg.rsf2csf` to get the complex schur form from the real as @msmdev suggested, which will give us the eigenvalues. These can then be used to warn the user in case we split a block of complex conjugates. However, `rsf2csf` expects a full schur decomposition by default.

Brandts and Scipy always perform the whole decomposition so `rsf2csf` will work. Didn't you also want the top eigenvalues to be returned to use them outside of msmtools?

> * `method = 'scipy'` always gives me E1 below, which seems to be caused by `slepc4py`

This is strange. I never had this issue. It must be related to your transition matrix....

> * In the example I'm looking at, `m = 6` would split a block of complex conjugates. With `method = 'krylov'`, this raises an error `Clustering P into `6` clusters will split a pair of conjugate eigenvalues. Choose one cluster more or less.`. However, when I use `method = 'brandts'`, I first get a warning about this and then E2 from below is raised. I think it would be good to make this consistent.

I see. Lets address this after the merge.

> * if `method='krylov'` but a dense matrix is passed, a warning may be nice to tell the user how to take advantage of SLEPSc

I don't think this is really necessary, since most people in molecular dynamics will use dense transition matrices, but still would profit from using SLEPc. They might be confused by such a warning...

> * I noticed fine differences between `method='brandts'` and `method='krylov'` for `m=2` in the memberships, but so small that `np.allclose` with default parameters still returns `True`. I only noticed this because when I plotted the memberships in the embedding, scvelo by default used a different colormap for one of the memberships that brandts gave. I don't know whether this means anything.

This doesn't sound troublesome, since I wouldn't expect that the methods return exactly the same memberships. 

> 
> ## E1
> ```python
> ---------------------------------------------------------------------------
> Error                                     Traceback (most recent call last)
> <ipython-input-26-5e22fe6c99aa> in <module>
>       1 # method = 'scipy'
>       2 gpcca = GPCCA(kernel_fwd.transition_matrix.A, method='scipy')
> ----> 3 gpcca.optimize(3)
> 
> ~/Projects/msmtools/msmtools/analysis/dense/gpcca.py in optimize(self, m, return_extra)
>    1324         # Calculate Schur matrix R and Schur vector matrix X, if not adequately given.
>    1325 
> -> 1326         self._do_schur_helper(max(m_list))
>    1327 
>    1328         # Initialize lists to collect results.
> 
> ~/Projects/msmtools/msmtools/analysis/dense/gpcca.py in _do_schur_helper(self, m)
>    1127                     self.X, self.R = _do_schur(self.P, self.eta, m, self.z, self.method)
>    1128             else:
> -> 1129                 self.X, self.R = _do_schur(self.P, self.eta, m, self.z, self.method)
>    1130 
>    1131     def minChi(self, m_min, m_max):
> 
> ~/Projects/msmtools/msmtools/analysis/dense/gpcca.py in _do_schur(P, eta, m, z, method)
>     250         Q = sorted_schur(P_bar, m, z, method) #Pbar!!!
>     251     else:
> --> 252         R, Q = sorted_schur(P_bar, m, z, method) #Pbar!!!
>     253         if m - 1 not in _find_twoblocks(R):
>     254             warnings.warn("Coarse-graining with " + str(m) + " states cuts through "
> 
> ~/Projects/msmtools/msmtools/util/sorted_schur.py in sorted_schur(P, m, z, method)
>     491             warnings.warn("Reordering of Schur matrix was inaccurate.")
>     492     elif method == 'scipy':
> --> 493         R, Q = sorted_scipy_schur(P, m, z=z)
>     494     elif method == 'krylov':
>     495         Q, _, _ = sorted_krylov_schur(P, m, z=z)
> 
> ~/Projects/msmtools/msmtools/util/sorted_schur.py in sorted_scipy_schur(P, m, z)
>     213         #cutoff = (np.abs(eigenval_in) + np.abs(eigenval_out)) / 2.0
>     214         cutoff = np.abs(top_eigenvals[m-1]) - 0.2
> --> 215         smallest_eigenval = np.abs(smallest_eigenvalue(P, z='SM'))
>     216         if cutoff < smallest_eigenval:
>     217             cutoff = smallest_eigenval
> 
> ~/Projects/msmtools/msmtools/util/sorted_schur.py in smallest_eigenvalue(P, z)
>     163         warnings.warn("The number of converged eigenpairs is too small.")
>     164     # Get the smallest eigenvalue.
> --> 165     smallest_eigenval = E.getEigenvalue(0)
>     166 
>     167     return smallest_eigenval
> 
> SLEPc/EPS.pyx in slepc4py.SLEPc.EPS.getEigenvalue()
> 
> Error: error code 63
> [0] EPSGetEigenvalue() line 450 in /Users/marius/slepc-3.13.1/src/eps/interface/epssolve.c
> [0] Argument out of range
> [0] Argument 2 out of range
> ```
> 
> ## E2
> ```python
> According to scipy.linalg.subspace_angles() X isn't an invariant subspace of P, since the subspace angles between the column spaces of P*X and X*R (resp. X, if you chose the Krylov-Schur method)aren't near zero. The subspace angles are: `[6.78576644e-03 2.42416841e-15 2.17546739e-15 1.91024389e-15
>  1.58665000e-15 7.86412512e-16]`
> ```

2020-05-03 12:25 UTC, Marius1311 commented
Update: I looked into an example in more detail to check whether `brands` and `krylov` are consistent. My example is a ~3500 x 3500 matrix with condition number ~1e18. 

I computed the first 20 eigenvalues using numpy dense `eigvals`, `scipy.sparse.linalg.eigs` and `scipy.linalg.schur` with sorting to get the complex schur form. Results are largely consistent, modulo ordering of complex conjugate pairs. See the spectrum in Fig 1 below. From this, I take that the following values of `m` would split a pair of complex conjugates: 6, 8, 10, 16, 18. 

## `method = 'brandts'`
`brands` current behaviour is to warn if `m` would cut through a block of complex conjugates. Afterwards, it continues and runs into error E2 from above. The method identifies correctly all numbers of `m` for which this would appear, plus `m=17`. I'm not sure why this happens. It issues a warning for this number, but does not run into E2 and instead spits out results. Also, it fails for `m=14` with E3 from below. Maybe need to adjust the tolerance here. 

## `method = 'krylov'`
`krylov`'s current behaviour is to issue the same warning as `brands` if `m` would cut through a block of complex conjugates , but to then give out E4 from below. It correctly identifies that using 6, 8, 10, 16 or 18 for `m` would do so, but it additionally issues the error for m=13, 14, 17.  Maybe these have a very small imaginary component? Also, `krylov` seems to struggle to return invariant subspaces. For m=4, 7, 9, it issues corresponding warnings, for every m>10, it fails, either because of splitting complex conjugates or because no invariant subspace was returned

![image](https://user-images.githubusercontent.com/24494650/80913676-b01ae080-8d46-11ea-8fec-4cfb255ea5c7.png)
Figure 1: Spectrum of the matrix. Numbers denote the sorting of eigenvalues according to their magnitude. 

## E3
```python
The rows of chi don't sum up to 1.0 after rescaling (with a absolute and relative tolerance of 2.220446049250313e-16).
```

## E4
```
Clustering P into `6` clusters will split a pair of conjugate eigenvalues. Choose one cluster more or less.
```

2020-05-03 13:33 UTC, msmdev commented
> Update: I looked into an example in more detail to check whether `brands` and `krylov` are consistent. My example is a ~3500 x 3500 matrix with condition number ~1e18.

This is a quite high condition number... I don't know, if anything regarding eigenvalues is really sane in this case. Schur should still work graciously anyway, but I don't really know, if this is still the case for Krylov-Schur.
`_initialize_rot_matrix` in gpcca.py would already raise an `ValueError` due to the overly high condition number here... or didn't it?? Did you execute the whole gpcca with this matrix??

> 
> I computed the first 20 eigenvalues using numpy dense `eigvals`, `scipy.sparse.linalg.eigs` and `scipy.linalg.schur` with sorting to get the complex schur form. Results are largely consistent, modulo ordering of complex conjugate pairs. See the spectrum in Fig 1 below. From this, I take that the following values of `m` would split a pair of complex conjugates: 6, 8, 10, 16, 18.
> 
> ## `method = 'brandts'`
> `brands` current behaviour is to warn if `m` would cut through a block of complex conjugates. Afterwards, it continues and runs into error E2 from above. The method identifies correctly all numbers of `m` for which this would appear, plus `m=17`. I'm not sure why this happens. It issues a warning for this number, but does not run into E2 and instead spits out results. Also, it fails for `m=14` with E3 from below. Maybe need to adjust the tolerance here.

For `brandts` splitting is currently first checked via `top_eigenvalues` in `sorted_schur` and later again via  `_find_twoblocks` in `_do_schur` (in the future I would only check it via `_find_twoblocks`). Anyway, in `top_eigenvalues` it tests `np.isclose(eigenval_in, np.conj(eigenval_out))` with `eigenval_in = top_eigenvals[m-1]` and `eigenval_out = top_eigenvals[m]`. Check those top eigenvalues returned from `top_eigenvalues`, mb this explains the m=17 prob?
Indeed, tolerance is too low...

> 
> ## `method = 'krylov'`
> `krylov`'s current behaviour is to issue the same warning as `brands` if `m` would cut through a block of complex conjugates , but to then give out E4 from below. It correctly identifies that using 6, 8, 10, 16 or 18 for `m` would do so, but it additionally issues the error for m=13, 14, 17. Maybe these have a very small imaginary component? 

Here both the warning and the indicator for the raise are issued via `top_eigenvalues` - so again check the results from there... The warning/error are only raised, if the `m`-th top eigenvalue and the complex conjugate of the `m+1`-th top eigenvalue are very close (standard tolerances of np.isclose). So a small imaginary component of the `m`-th top eigenvalue shouldn't cause this.

>Also, `krylov` seems to struggle to return invariant subspaces. For m=4, 7, 9, it issues corresponding warnings, for every m>10, it fails, either because of splitting complex conjugates or because no invariant subspace was returned

There is an issue of SLEPc `getInvariantSubspace` (which is used to get the Invariant Subspace). This seems to return the same as scipy.schur with sorting, but if too many eigenvalues converge (this happens often) the returned subspace is too big. Thus I just cut the extra dimensions of. Cuting the rest off seems to work in the cases I tested, but we don't know for sure... Mb. one would need to check, if the oversized subspace sometimes returned by `getInvariantSubspace` is still the same after cutting of the extra dimensions... You could check this.
> 
> ![image](https://user-images.githubusercontent.com/24494650/80913676-b01ae080-8d46-11ea-8fec-4cfb255ea5c7.png)
> Figure 1: Spectrum of the matrix. Numbers denote the sorting of eigenvalues according to their magnitude.
> 
> ## E3
> ```python
> The rows of chi don't sum up to 1.0 after rescaling (with a absolute and relative tolerance of 2.220446049250313e-16).
> ```
> 
> ## E4
> ```
> Clustering P into `6` clusters will split a pair of conjugate eigenvalues. Choose one cluster more or less.
> ```

2020-05-03 13:46 UTC, msmdev commented
@Marius1311 If indeed the problem stems from cutting off the excess dimensions of the subspace returned from SLEPc, one could try to construct a orthogonal basis from the returned subspace and hope that this subspace would have the requested dimension...

2020-05-03 22:22 UTC, michalk8 commented on msmtools/analysis/api.py
> +        return dense.gpcca.GPCCA(T, eta, z, method).optimize(m)
There was wrong numpy alias.

2020-05-03 22:25 UTC, michalk8 commented on msmtools/analysis/dense/gpcca.py
> +        raise ValueError(f"The number of rows `n={X.shape[0]}` of the Schur vector matrix X doesn't match "
I think they are considerably better for development. I've tested https://pypi.org/project/future-fstrings/ with Python3.5,
seems to work. As for Python2, I had different troubles with installation so I coudn't test it.

2020-05-03 22:33 UTC, michalk8 commented on msmtools/util/sorted_schur.py
> +            if not _slepc_msg_show or True:
Thanks for pointing it out, I had used this for debugging to test whether the message works.

2020-05-03 22:36 UTC, michalk8 commented on setup.py
>      setup_requires=['numpy', 'cython'],
I was using it just to get my installation working, but using setup from numpy fixed it, so there's no longer need for this.

2020-05-04 17:15 UTC, Marius1311 commented
I think my problems above were related to stability of krylov-schur and the conditioning of my matrix. I took the same, ill conditioned matrix and computed the top 20 eigenvalues using `np.linalg.eig`, `scipy.sparse.linalg.eigs`, `scipy.linalg.schur` and `krylov-schur`: 

![image](https://user-images.githubusercontent.com/24494650/80992594-087eda80-8e3a-11ea-8bff-10e09531108b.png)
They all look fairly similar, apart from krylov schur. Quantitatively, the maximum discrepancy between and of [`np.linalg.eig`, `scipy.sparse.linalg.eigs`, `scipy.linalg.schur`] is of the order 1e-6, so they are all very consistent, even for this ill conditioned matirx. However, take any of these and the maximum discrepancy to `krylov-schur` will 5 orders of magnitude larger. 

To confirm this, I looked into a similar matrix and is better conditioned. This second matrix is of the same size as the first one, is also sparse, has the same sparsity pattern but a condition number on the order 1e5, so much smaller than the original 1e18. I find the eigenvalues below:
![image](https://user-images.githubusercontent.com/24494650/80993049-b4c0c100-8e3a-11ea-9de4-2493745b7ffc.png)

You can't see much in these plots, but quantitatively, the results are the same: the maximum disceprancies between any of `np.linalg.eig`, `scipy.sparse.linalg.eigs`, `scipy.linalg.schur` are of the order 1e14, whereas their max discrepancy with `krylov-schur` is or the order 1e-8, so 6 orders of magnitude larger.

This discrepancy in eigenvalues is what (I think) causes the downstream trouble I experienced above. 

@msmdev , can you check whether you observe the same with transition matrices from your field of similar size (~3k x 3k)?

2020-05-04 17:19 UTC, Marius1311 commented
Oh, and could you maybe give me an example of a sparse matrix where `scipy.sparse.linalg.eigs` becomes instable? I'm wondering because in all my experiments, even with very ill-conditioned matrices, it always behaved very well.

2020-05-04 18:01 UTC, msmdev commented
> I think my problems above were related to stability of krylov-schur and the conditioning of my matrix. I took the same, ill conditioned matrix and computed the top 20 eigenvalues using `np.linalg.eig`, `scipy.sparse.linalg.eigs`, `scipy.linalg.schur` and `krylov-schur`:
> 
> ![image](https://user-images.githubusercontent.com/24494650/80992594-087eda80-8e3a-11ea-8bff-10e09531108b.png)
> They all look fairly similar, apart from krylov schur. Quantitatively, the maximum discrepancy between and of [`np.linalg.eig`, `scipy.sparse.linalg.eigs`, `scipy.linalg.schur`] is of the order 1e-6, so they are all very consistent, even for this ill conditioned matirx. However, take any of these and the maximum discrepancy to `krylov-schur` will be 5 orders of magnitude larger.
> 
> To confirm this, I looked into a similar matrix and is better conditioned. This second matrix is of the same size as the first one, is also sparse, has the same sparsity pattern but a condition number on the order 1e5, so much smaller than the original 1e18. I find the eigenvalues below:
> ![image](https://user-images.githubusercontent.com/24494650/80993049-b4c0c100-8e3a-11ea-9de4-2493745b7ffc.png)
> 
> You can't see much in these plots, but quantitatively, the results are the same: the maximum disceprancies between any of `np.linalg.eig`, `scipy.sparse.linalg.eigs`, `scipy.linalg.schur` are of the order 1e14, whereas their max discrepancy with `krylov-schur` is or the order 1e-8, so 6 orders of magnitude larger.

This is indeed very alarming - and suprising, since Krylov-Schur should by all means be superior to 
`np.linalg.eig`, `scipy.sparse.linalg.eigs` and comparable to `scipy.linalg.schur`...
**Could you please densify your matrix and try it again??** Mb. its related to bugs in the sparse implementation of PETSc/SLEPc...?! 
I had no such troubles with dense matrices (but I also didn't test large matrices...).

> 
> This discrepancy in eigenvalues is what (I think) causes the downstream trouble I experienced above.
> 
> @msmdev , can you check whether you observe the same with transition matrices from your field of similar size (~3k x 3k)?

Actually the largest matrices I have are of size (~2k x 2k).
I currently have no time to try them, but I could send you one?

2020-05-04 18:03 UTC, msmdev commented
> Oh, and could you maybe give me an example of a sparse matrix where `scipy.sparse.linalg.eigs` becomes instable? I'm wondering because in all my experiments, even with very ill-conditioned matrices, it always behaved very well.

I will take a look... it was a very small and simple matrix... (but it was dense...).

2020-05-04 18:31 UTC, Marius1311 commented
I meanwhile tried with densified matrices, same result. However, this is of course very limited, I only experimented with 2 matrices so far. We need to try this on a couple more large matrices to understand the behaviour, and to know when we can use `krylov-schur`

2020-05-04 18:33 UTC, Marius1311 commented
> > Oh, and could you maybe give me an example of a sparse matrix where `scipy.sparse.linalg.eigs` becomes instable? I'm wondering because in all my experiments, even with very ill-conditioned matrices, it always behaved very well.
> 
> I will take a look... it was a very small and simple matrix... (but it was dense...).

oh, okay, so I guess you were using just `scipy.linalg.eig` then? Would be great if you could find this matrix.

2020-05-04 19:06 UTC, msmdev commented
> I meanwhile tried with densified matrices, same result. However, this is of course very limited, I only experimented with 2 matrices so far. We need to try this on a couple more large matrices to understand the behaviour, and to know when we can use `krylov-schur`

Ok, that's sad. Mb. you could contact the slepc4.py/SLEPc developers to further inquire about this? Mb. I'm wrong in my expectations, but I would assume that Krylov-Schur shouldn't give degraded results compared to standard `scipy.linalg.eig`.

2020-05-05 08:21 UTC, Marius1311 commented
I will send them an email, but I think it would be really important if you could also try this out on a couple of matrices that you are typically dealing with, also ill conditioned ones to see how results compare with e.g. the standard schur decomposition.

2020-05-05 08:38 UTC, Marius1311 commented
When the user selects `method='brandts'` but passes a sparse matrix, how should we handle this? Currently, we raise a `ValueError`. I would prefer if we would issue a warning, densify the matrix and continue. @msmdev, what's your opinion?

2020-05-05 08:55 UTC, msmdev commented
> When the user selects `method='brandts'` but passes a sparse matrix, how should we handle this? Currently, we raise a `ValueError`. I would prefer if we would issue a warning, densify the matrix and continue. @msmdev, what's your opinion?

I totally agree :)

2020-05-05 10:41 UTC, msmdev commented
@michalk8 Just a quick question: have you already addressed all comments in the review? Then I could merge...

2020-05-05 10:55 UTC, michalk8 commented
@msmdev yes, I've addressed them.

2020-05-05 13:48 UTC, msmdev commented
> > > Oh, and could you maybe give me an example of a sparse matrix where `scipy.sparse.linalg.eigs` becomes instable? I'm wondering because in all my experiments, even with very ill-conditioned matrices, it always behaved very well.
> > 
> > 
> > I will take a look... it was a very small and simple matrix... (but it was dense...).
> 
> oh, okay, so I guess you were using just `scipy.linalg.eig` then? Would be great if you could find this matrix.

No I actually used `scipy.sparse.linalg.eigs`  on dense matrices to get a partial spectrum, since `scipy.linalg.eig` will only return the full spectrum.
I randomly generated transition matrices and tried it on them - sometimes it failed but I didn't store the matrices it failed on. I thinke the code I used to generate the matrices was something like:
```
# general non-reversible matrix
T = np.random.rand(8, 8)
T = T / T.sum(axis=1)[:, np.newaxis]
# add some transition state
Pex = np.zeros((9, 9))
Pex[0:8, 0:8] = T
e = 0.001
Pex[8, 7] = e
Pex[8, 8] = 1 - e
T = Pex
```
Anyhow, issues with `scipy.sparse.linalg.eigs` are not unknown, see e.g. 
https://github.com/scipy/scipy/issues/4987
https://github.com/scipy/scipy/issues/8307

2020-05-05 13:51 UTC, msmdev commented
> I will send them an email, but I think it would be really important if you could also try this out on a couple of matrices that you are typically dealing with, also ill conditioned ones to see how results compare with e.g. the standard schur decomposition.

How urgent is this? 
I'm currently very busy and this will take me some time... 
The fastest way would be, if I send you some matrices to test...

2020-05-05 16:15 UTC, merged

2020-05-06 07:45 UTC, Marius1311 commented
> > I will send them an email, but I think it would be really important if you could also try this out on a couple of matrices that you are typically dealing with, also ill conditioned ones to see how results compare with e.g. the standard schur decomposition.
> 
> How urgent is this?
> I'm currently very busy and this will take me some time...
> The fastest way would be, if I send you some matrices to test...

Sure, feel free to send some matrices, I can have run krylov-schur on them and compare with the other solvers.

2020-05-06 08:02 UTC, Marius1311 commented
Very exciting UPDATE:
- increasing the tolerance for krylov-schur from the default `1e-8` to `1e-16` solves my problems from above, for both the ill conditioned as well as for the well-conditioned matrix!
- On both the well conditioned and the ill conditioned matrix, the deviations of `krylov-schur` to the other methods are now of the same order of magnitude as the deviations of the other methods among each other!

So it was just a problem with setting the tolerance, because `krylov-schur` is an iterative solver. In practice, this won't matter all that much on well-conditioned matrices, but it becomes crucial for ill-conditioned matrices, otherwise, `krylov-schur` is no longer able to return invariant subspaces. I would therefore expose the tolerance as a parameter to the user - @msmdev , what's your opinion?

2020-05-06 08:09 UTC, msmdev commented
> Very exciting UPDATE:
> 
> * increasing the tolerance for krylov-schur from the default `1e-8` to `1e-16` solves my problems from above, for both the ill conditioned as well as for the well-conditioned matrix!
> * On both the well conditioned and the ill conditioned matrix, the deviations of `krylov-schur` to the other methods are now of the same order of magnitude as the deviations of the other methods among each other!
> 
> So it was just a problem with setting the tolerance, because `krylov-schur` is an iterative solver. In practice, this won't matter all that much on well-conditioned matrices, but it becomes crucial for ill-conditioned matrices, otherwise, `krylov-schur` is no longer able to return invariant subspaces. I would therefore expose the tolerance as a parameter to the user - @msmdev , what's your opinion?

Fantastic news! :)
Just one question: Does this also solve all problems with non-invariance of the subspace?
(Still the return of too many dimensions and the need to cut off seems troublesome to me... I will investigate this further with Jose, I think.)

2020-05-06 08:12 UTC, Marius1311 commented
I think it's a good idea to follow this up with Jose - I dind't look into this yet.

2020-05-06 08:12 UTC, msmdev commented
If speed isn't impaired dramatically I wouldn't expose the tolerance to the user (misuse or ignorance is preprogrammed here, I fear), but instead set it to machine precision (1e-16) as standard.

2020-05-06 08:13 UTC, msmdev commented
> I think it's a good idea to follow this up with Jose - I dind't look into this yet.

But all subspaces seem to be sane now? Or are there still complaints?

2020-05-06 10:05 UTC, msmdev commented
> > When the user selects `method='brandts'` but passes a sparse matrix, how should we handle this? Currently, we raise a `ValueError`. I would prefer if we would issue a warning, densify the matrix and continue. @msmdev, what's your opinion?
> 
> I totally agree :)

I added code to densify P, if it is sparse but `method != 'krylov'`:
https://github.com/msmdev/msmtools/blob/914c0dd03ef169e39e561ce8d18ffc7abd2956f3/msmtools/analysis/dense/gpcca.py#L1090

2020-05-06 12:37 UTC, msmdev commented
@Marius : Could you please file a pull request with the tolerance adapted to 1e-16 in `top_eigenvalues` `smallest_eigenvalue` and `sorted_krylov_schur`?
Is this also fixing the subspace issue?